import "./globals.css";
import type { Metadata } from "next";
import Favicon from "../assets/images/FaviconTransparent.png";

export const metadata: Metadata = {
  title: "Savoury Search",
  description: "Generated by create next app",
  icons: Favicon.src,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">{children}</body>
    </html>
  );
}
